name: lemonpie
channels:
  - corazonlabs
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pandas>=1.2.2
  - requests
  - pyyaml
  - addict
  - pytorch>=1.7
  - fastai<2.0.0
  - nbdev
  - fastcore>=1.3.8
  - torchvision>=0.8
  - matplotlib
  - fastprogress>=0.2.4
  - scikit-learn
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pip:
    - ray[all] >= 1.2
