name: lemonade
channels:
  - fastai
  - pytorch
  - defaults
dependencies:
  - pandas>=1.2.2
  - requests
  - pyyaml
  - addict>=2.3.0
  - pytorch>=1.7.0
  - fastai<=1.0.57
  - fastcore>=1.3.8
  - torchvision>=0.8
  - matplotlib
  - fastprogress>=0.2.4
  - scikit-learn
