name: lemonpie
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - addict=2.4.0
  - black=22.6.0 # dev
  - fastai=1.0.57
  - fastcore=1.3
  - fastprogress=1.0
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib=3.3.4
  - nbdev=1.1.13
  - pandas=1.2.3
  - pydocstyle=6.1.1 # dev
  - pytorch-lightning=1.7.0
  - pytorch=1.12.1
  - pyyaml=5.4.1
  - requests=2.25.1
  - scikit-learn=0.24.1
  - tensorboard-2.10.0
  - torchmetrics-0.9.3
  - torchvision=0.13.1
  - pip:
      - ray[all]==1.5.1
