name: lemonpie
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - requests=2.25.1
  - pyyaml=5.4.1
  - addict=2.4.0
  - pytorch=1.8.1
  - fastai=1.0.57
  - nbdev=1.1.13
  - fastcore=1.3
  - torchvision=0.9.1
  - matplotlib=3.3.4
  - fastprogress=1.0
  - scikit-learn=0.24.1
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pytorch-lightning-0.8.5
  - tensorboard-1.15.0
  - torchmetrics-0.9.3
  - pip:
      - ray[all]==1.5.1
