# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PATH": "01_preprocessing_clean.ipynb",
         "PATH_1K": "01_preprocessing_clean.ipynb",
         "PATH_10K": "01_preprocessing_clean.ipynb",
         "PATH_20K": "01_preprocessing_clean.ipynb",
         "PATH_100K": "01_preprocessing_clean.ipynb",
         "FILENAMES": "01_preprocessing_clean.ipynb",
         "SYNTHEA_DATAGEN_DATES": "01_preprocessing_clean.ipynb",
         "CONDITIONS": "01_preprocessing_clean.ipynb",
         "LABELS": "01_preprocessing_clean.ipynb",
         "CUTOFF_AGE": "01_preprocessing_clean.ipynb",
         "LOG_NUMERICALIZE_EXCEP": "01_preprocessing_clean.ipynb",
         "read_raw_ehrdata": "01_preprocessing_clean.ipynb",
         "split_patients": "01_preprocessing_clean.ipynb",
         "split_ehr_dataset": "01_preprocessing_clean.ipynb",
         "cleanup_pts": "01_preprocessing_clean.ipynb",
         "cleanup_obs": "01_preprocessing_clean.ipynb",
         "cleanup_algs": "01_preprocessing_clean.ipynb",
         "cleanup_crpls": "01_preprocessing_clean.ipynb",
         "cleanup_meds": "01_preprocessing_clean.ipynb",
         "cleanup_img": "01_preprocessing_clean.ipynb",
         "cleanup_procs": "01_preprocessing_clean.ipynb",
         "cleanup_cnds": "01_preprocessing_clean.ipynb",
         "cleanup_immns": "01_preprocessing_clean.ipynb",
         "cleanup_dataset": "01_preprocessing_clean.ipynb",
         "extract_ys": "01_preprocessing_clean.ipynb",
         "insert_age": "01_preprocessing_clean.ipynb",
         "clean_raw_ehrdata": "01_preprocessing_clean.ipynb",
         "load_cleaned_ehrdata": "01_preprocessing_clean.ipynb",
         "load_ehr_vocabcodes": "01_preprocessing_clean.ipynb",
         "EhrVocab": "02_preprocessing_vocabs.ipynb",
         "ObsVocab": "02_preprocessing_vocabs.ipynb",
         "EhrVocabList": "02_preprocessing_vocabs.ipynb",
         "get_all_emb_dims": "02_preprocessing_vocabs.ipynb"}

modules = ["preprocessing/clean.py",
           "preprocessing/vocab.py"]

doc_url = "https://corazonlabs.github.io/lemonade/"

git_url = "https://github.com/corazonlabs/lemonade/tree/master/"

def custom_doc_links(name): return None
