# infrastructure items in config
config:
  name: cnn_base
  path: #update this to absolute path of EXPERIMENT_STORE (e.g. '/home/vinod/.lemonpie/experiments')
  desc: Baseline settings for EHR_CNN experiments
  checkpoint_path: #update this to absolute path of MODEL_STORE (e.g. '/home/vinod/.lemonpie/models')

params:
  data_params:
    dataset_path: #update this to absolute path of dataset (e.g. '/home/vinod/.lemonpie/datasets/synthea/1K')
    labels: ['diabetes', 'stroke', 'alzheimers', 'coronaryheart']
    age_start: 0
    age_stop: 20
    age_in_months: False
    bs: 128
    num_workers: 0
    lazy_load_gpu: True

  optim_params:
    optim: Adagrad
    lr: 0.01
    lr_decay: 0
    weight_decay: 0

  model_params:
    model: CNN
    Î±d: 0.5736
    linear_layers: 4
    initrange: 0.3
    bn: True
    input_drp: 0.3
    linear_drp: 0.3
    zero_bn: False
